#%RAML 1.0 DataType
type: object
properties:
  id: string
  hash:
    type: string
    pattern: ^([A-Fa-f0-9]{64})$
    description: SHA256 encoded MAC address
  date: datetime-only
example: |
  {
    "id": "7654",
    "hash": "50d858e0985ecc7f60418aaf0cc5ab587f42c2570a884095a9e8ccacd0f6545c",
    "date": "2016-12-01T09:24:54.508"
  }
