#%RAML 1.0 DataType
type: object
properties:
  id: string
  from: datetime-only
  to: datetime-only
example: |
  {
    "id": "654",
    "from": "2016-11-28T12:52:54.635",
    "to": "2016-11-28T13:04:12.863"
  }
